#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Constants
#define FIDO2_MAX_CREDENTIALS 10
#define FIDO2_CREDENTIAL_ID_SIZE 32
#define FIDO2_RP_ID_MAX_SIZE 128
#define FIDO2_USER_ID_MAX_SIZE 64
#define FIDO2_USER_NAME_MAX_SIZE 64

// CTAP2 Status codes
#define CTAP2_OK 0x00
#define CTAP2_ERR_INVALID_COMMAND 0x01
#define CTAP2_ERR_INVALID_PARAMETER 0x02
#define CTAP2_ERR_INVALID_LENGTH 0x03
#define CTAP2_ERR_INVALID_SEQ 0x04
#define CTAP2_ERR_TIMEOUT 0x05
#define CTAP2_ERR_CHANNEL_BUSY 0x06
#define CTAP2_ERR_LOCK_REQUIRED 0x0A
#define CTAP2_ERR_INVALID_CHANNEL 0x0B
#define CTAP2_ERR_CBOR_UNEXPECTED_TYPE 0x11
#define CTAP2_ERR_INVALID_CBOR 0x12
#define CTAP2_ERR_MISSING_PARAMETER 0x14
#define CTAP2_ERR_LIMIT_EXCEEDED 0x15
#define CTAP2_ERR_UNSUPPORTED_EXTENSION 0x16
#define CTAP2_ERR_CREDENTIAL_EXCLUDED 0x19
#define CTAP2_ERR_PROCESSING 0x21
#define CTAP2_ERR_INVALID_CREDENTIAL 0x22
#define CTAP2_ERR_USER_ACTION_PENDING 0x23
#define CTAP2_ERR_OPERATION_PENDING 0x24
#define CTAP2_ERR_NO_OPERATIONS 0x25
#define CTAP2_ERR_UNSUPPORTED_ALGORITHM 0x26
#define CTAP2_ERR_OPERATION_DENIED 0x27
#define CTAP2_ERR_KEY_STORE_FULL 0x28
#define CTAP2_ERR_NO_OPERATION_PENDING 0x2A
#define CTAP2_ERR_UNSUPPORTED_OPTION 0x2B
#define CTAP2_ERR_INVALID_OPTION 0x2C
#define CTAP2_ERR_KEEPALIVE_CANCEL 0x2D
#define CTAP2_ERR_NO_CREDENTIALS 0x2E
#define CTAP2_ERR_USER_ACTION_TIMEOUT 0x2F
#define CTAP2_ERR_NOT_ALLOWED 0x30
#define CTAP2_ERR_PIN_INVALID 0x31
#define CTAP2_ERR_PIN_BLOCKED 0x32
#define CTAP2_ERR_PIN_AUTH_INVALID 0x33
#define CTAP2_ERR_PIN_AUTH_BLOCKED 0x34
#define CTAP2_ERR_PIN_NOT_SET 0x35
#define CTAP2_ERR_PIN_REQUIRED 0x36
#define CTAP2_ERR_PIN_POLICY_VIOLATION 0x37
#define CTAP2_ERR_PIN_TOKEN_EXPIRED 0x38
#define CTAP2_ERR_REQUEST_TOO_LARGE 0x39
#define CTAP2_ERR_ACTION_TIMEOUT 0x3A
#define CTAP2_ERR_UP_REQUIRED 0x3B

// CTAP2 Commands
#define CTAP2_CMD_MAKE_CREDENTIAL 0x01
#define CTAP2_CMD_GET_ASSERTION 0x02
#define CTAP2_CMD_GET_INFO 0x04
#define CTAP2_CMD_CLIENT_PIN 0x06
#define CTAP2_CMD_RESET 0x07
#define CTAP2_CMD_GET_NEXT_ASSERTION 0x08
#define CTAP2_CMD_BIO_ENROLLMENT 0x09
#define CTAP2_CMD_CREDENTIAL_MANAGEMENT 0x0A
#define CTAP2_CMD_SELECTION 0x0B
#define CTAP2_CMD_VENDOR_FIRST 0x40
#define CTAP2_CMD_VENDOR_LAST 0xBF

// CBOR Major types
#define CBOR_MAJOR_UNSIGNED 0
#define CBOR_MAJOR_NEGATIVE 1
#define CBOR_MAJOR_BYTES 2
#define CBOR_MAJOR_TEXT 3
#define CBOR_MAJOR_ARRAY 4
#define CBOR_MAJOR_MAP 5
#define CBOR_MAJOR_TAG 6
#define CBOR_MAJOR_SIMPLE 7

// CBOR Additional info values
#define CBOR_FALSE 20
#define CBOR_TRUE 21
#define CBOR_NULL 22
#define CBOR_UNDEFINED 23
